### PR TITLE
update styling & change layout 💅

### PR DESCRIPTION
**Pull request by stefanmiodrag**
There we go! Let's do a pull request instead 😅

### CODE REVIEW

**Comment by gr2m** [comment]
@stefanmiodrag how do things look like for ya? No worries if you got busy, just let us know :)

**Comment by stefanmiodrag** [comment]
Hey @gr2m 

Yeah, sorry. Been busy these past days. I'll try to get the time to go through it tomorrow or on Tuesday.

**Comment by stefanmiodrag** [comment]
Added underline to links inside content div.
Removed the button class I removed, ie; the submit link is no longer a button.
Moved <head> outside of <main>.

Let me know if I missed anything, thanks! 👍

**Comment by jimthoburn** [comment]
Hi Stefan,

It looks like some of the new design may have been lost in this commit:
https://github.com/octonews/octonews/pull/34/commits/bd60238b5dceccf29c7e6bc4bdbd8296af6293f1

I made a new branch with the commits that came before this one, and did my best to remove the extra code from the merge…
https://github.com/octonews/octonews/commits/new-design-by-stefan-and-jim

Here are the steps I followed, if you want to try them…

1. Went one step back in history, in the “new-design” branch:
```
git checkout d952674cc3079b135eadc14e37e19cf634846788
```
2. Created a new branch:
```
git checkout -b new-design-by-stefan-and-jim d952674cc3079b135eadc14e37e19cf634846788
```
3. Removed the code marked “Updated upstream”: https://github.com/octonews/octonews/commit/37602a5aca31d03c8c4159b70d6ee770b8b25696
4. Added a new style for a “Call to Action” that can be applied to any element, including links: https://github.com/octonews/octonews/commit/6ed4c9f7730c6b40925922be0d2d97ba4953d6e6
5. Rebased the branch from master:
```
git rebase master
```

If you’re short on time, you can check out the [new-design-by-stefan-and-jim](https://github.com/octonews/octonews/tree/new-design-by-stefan-and-jim) branch. Feel free to make more edits and a new pull request. You may want to adjust the text color. I may have accidentally reverted it to black.

new-design

**Comment by gr2m** [comment]
ping @stefanmiodrag :)

**Comment by gr2m** [comment]
Hey @stefanmiodrag do you still want to have a look at this? No worries if you are too busy, just let us know. I’ll move the project forward this weekend, I hope to launch it soon

**Comment by stefanmiodrag** [comment]
Hey @gr2m, yeah sorry, I've been really busy lately. I won't be able to do any work on this for a while.

**Pull request closed without merging**
